name: vfr-function-routes-app

services:
  - name: web
    type: web
    ports:
      - port: 8080
        protocol: http
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
    build:
      dockerfile: ./Dockerfile
